language: node_js
services:
  - docker

before_install:
  - docker build -t tjxtan/examplereactapp -f Dockerfile.dev .

script:
<<<<<<< HEAD
 - docker run tjxtan/examplereactapp npm run test -- --coverage