language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - docker build -t tjxtan/examplereactapp -f Dockerfile .

script:

 - docker run tjxtan/examplereactapp npm run test -- --coverage